# Minimal CMake for building STARK prover components
# Usage: cmake -C build_stark.cmake -B build_stark ..

set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(BUILD_GROTH16 OFF CACHE BOOL "" FORCE)
set(BUILD_BASEFOLD_RAA ON CACHE BOOL "" FORCE)
set(BUILD_FORMAL_PROOF_CIRCUITS OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_ACCUMULATOR OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_BLOCKCHAIN OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_POS OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_SIGNATURES OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_STREAM OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_CHANNEL OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_EXCHANGE OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_VRF OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_TREES OFF CACHE BOOL "" FORCE)
set(BUILD_CMPTR_COMMITMENTS OFF CACHE BOOL "" FORCE)
